// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/color-modes/SpectralMode.tsx": () => import("../components/mockups/color-modes/SpectralMode.tsx"),
  "./components/mockups/color-modes/TealCore.tsx": () => import("../components/mockups/color-modes/TealCore.tsx")
};
